### ISSUE TITLE
Something wrong with solution to puzzle 11?

### ISSUE THREAD

**Issue by polettix** [petertseng/adventofcode-rb-2016#4]
Hi! I also wrote on reddit about this, but maybe here is the best way to discuss.

My puzzle input is as follows:

```
The first floor contains a promethium generator and a promethium-compatible microchip.
The second floor contains a cobalt generator, a curium generator, a ruthenium generator, and a plutonium generator.
The third floor contains a cobalt-compatible microchip, a curium-compatible microchip, a ruthenium-compatible microchip, and a plutonium-compatible microchip.
The fourth floor contains nothing relevant.
```

When running your code, it provides the following answers:

```
$ ruby 11.rb 11.input
35
57
$ ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

While the second answer is correct (and my congratulations, by the way!), the first one is off by 2 (the correct answer is 33).

I though you might be interested... even after 4 years and (almost) a month!

**Comment by petertseng** [comment]
This is very interesting! First, I'd like to thank you for reporting this. I have now fixed this. I'd like to take a moment to explain the problem and then reflect.

# Culprit commit

First, we see that since the answer was **too high**, the code was **missing** a legal move it could have made. I looked back at commit history and the commit https://github.com/petertseng/adventofcode-rb-2016/commit/fde1982c89f041c7f0c82b00bc70135e94239746 entitled "only generate legal moves" was the culprit. Before that commit, the code got the correct answer of 33. So what happened?

# Problem explanation

There is one specific situation where that code failed to generate a legal move:

Consider two floors with the following contents:

    The first floor contains a AAA generator, a AAA-compatible microchip, and a BBB generator.
    The second floor contains a BBB-compatible microchip.

In this case, one legal move is to move both generators from the first floor to the second. However, the old code did not consider this legal! The old code was only considering generators from the first floor in isolation, and reasoned that since the AAA generator can't move to floor 2 alone (that would leave the AAA chip to fry), it also can't move together with the BBB generator. This would usually be correct but is incorrect when AAA and BBB are the only generators on that floor! In that case, moving the two generators together means the AAA chip is safe! So the fix is to teach the code about this case. If there are only those two generators, moving them together to the second floor is legal.

# Reflection

That means four years ago I must have made this optimisation without verifying that it was fully correct. Surely I would have verified that it still produces the same answer on my own input, but it didn't catch this particular case on this particular input. It would have been better to have full verification - at every step that this optimisation is performed, check it against the unoptimised version and see whether it either produced an illegal move or failed to produce a legal move. I now added that functionality in another branch, https://github.com/petertseng/adventofcode-rb-2016/tree/debug11, and this time it reports that that the unoptimised version matches the optimised version... for this particular optimisation, at least. There are a few other optimisations that I now no longer recall whether I fully verified...

**Comment by polettix** [comment]
Wow... this was fast! 👍
